// actions/auditor.ts
"use server";
import { prisma } from "@/lib/prisma";
import { assertUserAccess, getSession } from "@/lib/security";
// ADDED MISSING IMPORTS: CertLevel and CertStatus are usually generated by Prisma
import { Role, RecipeStatus, Prisma, CertLevel, CertStatus } from "@prisma/client";
import { revalidatePath } from "next/cache";
/**
 * Retrieves recipes currently waiting for digital verification (Level 1 Queue).
 * Direct database query wrapped securely.
 */
export async function getPendingAuditQueue() {
    const session = await getSession();

    // 🚨 SECURITY: Ensure only authorized auditors or admins can view the queue
    await assertUserAccess(session, [Role.nutritionist_auditor, Role.platform_admin]);

    try {
        const queue = await prisma.recipe.findMany({
            where: { status: RecipeStatus.PENDING },
            include: {
                restaurant: {
                    select: {
                        id: true,
                        business_name: true,
                        cert_level: true,
                        slug: true,
                    },
                },
                ingredients: {
                    include: {
                        ingredient_item: {
                            select: {
                                name: true,
                                calories_per_g: true,
                                allergens: true,
                            },
                        },
                    },
                },
            },
            orderBy: { id: "asc" },
        });

        return {
            success: true,
            message: "Pending auditor queue loaded successfully.",
            data: queue,
        };
    } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : "Failed to load audit queue.";
        return { success: false, message: errorMessage };
    }
}

/**
 * Level 1 Verification Sign-off.
 * Updates recipe status, logs feedback, and preserves an immutable snapshot if approved.
 */
export async function verifyRecipeLevel1(
    recipeId: number,
    approved: boolean,
    rejectionReason?: string
) {
    // 🚨 SECURITY: Guardrail must execute outside the try/catch block to allow NEXT_REDIRECT to bubble [3]
    const session = await getSession();
    await assertUserAccess(session, [Role.nutritionist_auditor, Role.platform_admin]);

    try {
        if (!approved && (!rejectionReason || !rejectionReason.trim())) {
            return { success: false, message: "A rejection reason must be logged for declined recipes." };
        }

        const result = await prisma.$transaction(async (tx) => {
            // Fetch recipe before updating to ensure it exists and map its current data
            const existingRecipe = await tx.recipe.findUnique({
                where: { id: recipeId },
                include: {
                    ingredients: {
                        include: {
                            ingredient_item: true,
                        },
                    },
                },
            });

            if (!existingRecipe) {
                throw new Error("Target recipe not found.");
            }

            const status = approved ? RecipeStatus.APPROVED : RecipeStatus.REJECTED;

            const updatedRecipe = await tx.recipe.update({
                where: { id: recipeId },
                data: {
                    status,
                    rejection_reason: approved ? null : rejectionReason,
                },
                include: {
                    ingredients: {
                        include: {
                            ingredient_item: true,
                        },
                    },
                },
            });

            // If approved, create an immutable JSON snapshot of the state
            if (approved) {
                await tx.recipeVersion.create({
                    data: {
                        recipe_id: recipeId,
                        snapshot: JSON.parse(JSON.stringify(updatedRecipe)),
                    },
                });
            }

            // Log verification execution in system Audit Trails
            await tx.auditLog.create({
                data: {
                    actor_id: session!.id,
                    restaurant_id: updatedRecipe.restaurant_id,
                    recipe_id: recipeId,
                    action: approved ? "RECIPE_VERIFIED_L1" : "RECIPE_REJECTED_L1",
                    payload: {
                        rejection_reason: approved ? null : rejectionReason,
                        calculated_calories: updatedRecipe.calories.toString(),
                    },
                },
            });

            return updatedRecipe;
        });

        revalidatePath("/auditor/queue");
        revalidatePath(`/auditor/queue/${recipeId}`);
        revalidatePath("/owner/recipes");

        return {
            success: true,
            message: approved
                ? "Recipe successfully certified for Level 1 compliance."
                : "Recipe rejected. Notification feedback logged for restaurant owner.",
        };
    } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : "Failed to execute digital verification.";
        return { success: false, message: errorMessage };
    }
}
// Add these actions to the bottom of actions/auditor.ts

interface SubmitAuditPayload {
    restaurantId: number;
    hasDedicatedAllergenZones: boolean;
    usesStandardizedRecipes: boolean;
}

/**
 * Submits the site audit questionnaire results (Level 2).
 * Automatically upgrades the restaurant to LEVEL_3 if 100% of its recipes are approved.
 */
export async function submitPhysicalSiteAudit(payload: SubmitAuditPayload) {
    const session = await getSession();
    await assertUserAccess(session, [Role.nutritionist_auditor, Role.platform_admin]);

    try {
        const result = await prisma.$transaction(async (tx) => {
            // 1. Create or update the KitchenControlProfile
            const profile = await tx.kitchenControlProfile.upsert({
                where: { restaurantId: payload.restaurantId },
                update: {
                    hasDedicatedAllergenZones: payload.hasDedicatedAllergenZones,
                    usesStandardizedRecipes: payload.usesStandardizedRecipes,
                },
                create: {
                    restaurantId: payload.restaurantId,
                    hasDedicatedAllergenZones: payload.hasDedicatedAllergenZones,
                    usesStandardizedRecipes: payload.usesStandardizedRecipes,
                },
            });

            // 2. Count recipes
            const totalRecipesCount = await tx.recipe.count({
                where: { restaurant_id: payload.restaurantId },
            });

            const unapprovedRecipesCount = await tx.recipe.count({
                where: {
                    restaurant_id: payload.restaurantId,
                    status: { not: RecipeStatus.APPROVED },
                },
            });

            const isFullyCompliant = totalRecipesCount > 0 && unapprovedRecipesCount === 0;

            // 3. Upgrade certification level
            const updatedRestaurant = await tx.restaurant.update({
                where: { id: payload.restaurantId },
                data: {
                    cert_level: isFullyCompliant ? CertLevel.LEVEL_3 : CertLevel.LEVEL_2,
                    cert_status: isFullyCompliant ? CertStatus.ACTIVE : CertStatus.PENDING,
                },
            });

            // 4. Log the audit
            await tx.auditLog.create({
                data: {
                    actor_id: session!.id,
                    restaurant_id: payload.restaurantId,
                    action: "PHYSICAL_SITE_AUDIT_LOGGED",
                    payload: {
                        hasDedicatedAllergenZones: payload.hasDedicatedAllergenZones,
                        usesStandardizedRecipes: payload.usesStandardizedRecipes,
                        assigned_tier: isFullyCompliant ? "LEVEL_3" : "LEVEL_2",
                    } as Prisma.InputJsonValue, // Explicitly cast to prevent type mismatch
                },
            });

            return { profile, restaurant: updatedRestaurant };
        });

        revalidatePath("/auditor/queue");
        revalidatePath(`/auditor/audit/${payload.restaurantId}`);

        return {
            success: true,
            message: result.restaurant.cert_level === CertLevel.LEVEL_3
                ? "Establishment successfully certified as LEVEL 3 (ACTIVE)."
                : "Establishment certified as LEVEL 2. Complete pending digital recipes to unlock Level 3 status.",
        };
    } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : "Failed to record physical site audit.";
        return { success: false, message: errorMessage };
    }
}